#############################################################################
# Makefile for building: DE
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  DE.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug -o Makefile DE.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -std=gnu11 -g -D_REENTRANT -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -std=c++0x -D_REENTRANT -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -I../LIB -I../../Data -I../../AVR/Macros -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DE1.0.0
DISTDIR = /tmp/Examples/QT/DE/.tmp/DE1.0.0
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		toolbar.cpp \
		MainWindow.cpp \
		MainTreeWidget.cpp \
		LocalHostWidget.cpp \
		fdefault.cpp \
		fdevice.cpp \
		desettings.cpp \
		../LIB/smo.cpp \
		../LIB/zvvlib.cpp \
		../LIB/deviceinfo.cpp \
		../LIB/deplugin.cpp \
		../LIB/fcomport.cpp \
		../LIB/fmessage.cpp \
		../LIB/smolib.cpp \
		../LIB/LogTree.cpp \
		../LIB/treelib.cpp \
		../LIB/config.cpp \
		../LIB/SerialPort.cpp \
		../../AVR/Macros/CRC.c \
		../../AVR/Macros/Offseters.c \
		../LIB/g8enum.cpp \
		../LIB/label.cpp \
		smoui.cpp \
		smouipageheader.cpp \
		smouitextline.cpp \
		../LIB/byte.cpp \
		../LIB/realtime32.cpp qrc_DE.cpp \
		moc_toolbar.cpp \
		moc_MainWindow.cpp \
		moc_MainTreeWidget.cpp \
		moc_LocalHostWidget.cpp \
		moc_fdefault.cpp \
		moc_fdevice.cpp \
		moc_fcomport.cpp \
		moc_LogTree.cpp \
		moc_config.cpp \
		moc_SerialPort.cpp \
		moc_g8enum.cpp \
		moc_desettings.cpp \
		moc_label.cpp \
		moc_smoui.cpp
OBJECTS       = main.o \
		toolbar.o \
		MainWindow.o \
		MainTreeWidget.o \
		LocalHostWidget.o \
		fdefault.o \
		fdevice.o \
		desettings.o \
		smo.o \
		zvvlib.o \
		deviceinfo.o \
		deplugin.o \
		fcomport.o \
		fmessage.o \
		smolib.o \
		LogTree.o \
		treelib.o \
		config.o \
		SerialPort.o \
		CRC.o \
		Offseters.o \
		g8enum.o \
		label.o \
		smoui.o \
		smouipageheader.o \
		smouitextline.o \
		byte.o \
		realtime32.o \
		qrc_DE.o \
		moc_toolbar.o \
		moc_MainWindow.o \
		moc_MainTreeWidget.o \
		moc_LocalHostWidget.o \
		moc_fdefault.o \
		moc_fdevice.o \
		moc_fcomport.o \
		moc_LogTree.o \
		moc_config.o \
		moc_SerialPort.o \
		moc_g8enum.o \
		moc_desettings.o \
		moc_label.o \
		moc_smoui.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		DE.pro app_config.h \
		toolbar.h \
		MainWindow.h \
		MainTreeWidget.h \
		LocalHostWidget.h \
		fdefault.h \
		fdevice.h \
		../LIB/smo.h \
		../LIB/zvvlib.h \
		../../Data/SmoRecord.h \
		../LIB/deviceinfo.h \
		../LIB/deplugin.h \
		../LIB/fcomport.h \
		../LIB/fmessage.h \
		../LIB/smolib.h \
		../LIB/LogTree.h \
		../LIB/treelib.h \
		../LIB/config.h \
		../LIB/SerialPort.h \
		../LIB/zvvcompiler.h \
		../LIB/debugqt.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../../Data/SmoBusData.h \
		../LIB/delib.h \
		../LIB/g8enum.h \
		desettings.h \
		../LIB/label.h \
		smoui.h \
		smouipageheader.h \
		smouitextline.h \
		../LIB/byte.h \
		../LIB/realtime32.h main.cpp \
		toolbar.cpp \
		MainWindow.cpp \
		MainTreeWidget.cpp \
		LocalHostWidget.cpp \
		fdefault.cpp \
		fdevice.cpp \
		desettings.cpp \
		../LIB/smo.cpp \
		../LIB/zvvlib.cpp \
		../LIB/deviceinfo.cpp \
		../LIB/deplugin.cpp \
		../LIB/fcomport.cpp \
		../LIB/fmessage.cpp \
		../LIB/smolib.cpp \
		../LIB/LogTree.cpp \
		../LIB/treelib.cpp \
		../LIB/config.cpp \
		../LIB/SerialPort.cpp \
		../../AVR/Macros/CRC.c \
		../../AVR/Macros/Offseters.c \
		../LIB/g8enum.cpp \
		../LIB/label.cpp \
		smoui.cpp \
		smouipageheader.cpp \
		smouitextline.cpp \
		../LIB/byte.cpp \
		../LIB/realtime32.cpp
QMAKE_TARGET  = DE
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = DE


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DE.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		DE.pro \
		DE.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug -o Makefile DE.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
DE.pro:
DE.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug -o Makefile DE.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents DE.qrc $(DISTDIR)/
	$(COPY_FILE) --parents app_config.h toolbar.h MainWindow.h MainTreeWidget.h LocalHostWidget.h fdefault.h fdevice.h ../LIB/smo.h ../LIB/zvvlib.h ../../Data/SmoRecord.h ../LIB/deviceinfo.h ../LIB/deplugin.h ../LIB/fcomport.h ../LIB/fmessage.h ../LIB/smolib.h ../LIB/LogTree.h ../LIB/treelib.h ../LIB/config.h ../LIB/SerialPort.h ../LIB/zvvcompiler.h ../LIB/debugqt.h ../../AVR/Macros/CRC.h ../../AVR/Macros/Offseters.h ../../Data/SmoBusData.h ../LIB/delib.h ../LIB/g8enum.h desettings.h ../LIB/label.h smoui.h smouipageheader.h smouitextline.h ../LIB/byte.h ../LIB/realtime32.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp toolbar.cpp MainWindow.cpp MainTreeWidget.cpp LocalHostWidget.cpp fdefault.cpp fdevice.cpp desettings.cpp ../LIB/smo.cpp ../LIB/zvvlib.cpp ../LIB/deviceinfo.cpp ../LIB/deplugin.cpp ../LIB/fcomport.cpp ../LIB/fmessage.cpp ../LIB/smolib.cpp ../LIB/LogTree.cpp ../LIB/treelib.cpp ../LIB/config.cpp ../LIB/SerialPort.cpp ../../AVR/Macros/CRC.c ../../AVR/Macros/Offseters.c ../LIB/g8enum.cpp ../LIB/label.cpp smoui.cpp smouipageheader.cpp smouitextline.cpp ../LIB/byte.cpp ../LIB/realtime32.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_DE.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_DE.cpp
qrc_DE.cpp: DE.qrc \
		PNG/link.png \
		PNG/help.png \
		PNG/refresh.png \
		PNG/clock_old.png \
		PNG/folder.png \
		PNG/play.png \
		PNG/write.png \
		PNG/device.png \
		PNG/warning.png \
		PNG/delete.png \
		PNG/info.png \
		PNG/key.png \
		PNG/PC.png \
		PNG/PCnet.png \
		PNG/off.png \
		PNG/ok.png \
		PNG/error.png \
		PNG/control.png \
		PNG/PCadd.png \
		PNG/usb.png \
		PNG/deviceAdd.png \
		PNG/data.png \
		PNG/group0.png \
		PNG/group1.png \
		PNG/key_delete.png \
		PNG/save.png \
		PNG/group2.png \
		PNG/next.png \
		PNG/Well.png \
		PNG/date.png \
		PNG/group3.png \
		PNG/blocks.png \
		PNG/UserGroup.png \
		PNG/clock.png \
		PNG/cancel.png \
		PNG/gear.png \
		PNG/stop.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name DE DE.qrc -o qrc_DE.cpp

compiler_moc_header_make_all: moc_toolbar.cpp moc_MainWindow.cpp moc_MainTreeWidget.cpp moc_LocalHostWidget.cpp moc_fdefault.cpp moc_fdevice.cpp moc_fcomport.cpp moc_LogTree.cpp moc_config.cpp moc_SerialPort.cpp moc_g8enum.cpp moc_desettings.cpp moc_label.cpp moc_smoui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_toolbar.cpp moc_MainWindow.cpp moc_MainTreeWidget.cpp moc_LocalHostWidget.cpp moc_fdefault.cpp moc_fdevice.cpp moc_fcomport.cpp moc_LogTree.cpp moc_config.cpp moc_SerialPort.cpp moc_g8enum.cpp moc_desettings.cpp moc_label.cpp moc_smoui.cpp
moc_toolbar.cpp: toolbar.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include toolbar.h -o moc_toolbar.cpp

moc_MainWindow.cpp: MainTreeWidget.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/LogTree.h \
		desettings.h \
		../LIB/config.h \
		MainWindow.h \
		MainWindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MainWindow.h -o moc_MainWindow.cpp

moc_MainTreeWidget.cpp: ../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		MainTreeWidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MainTreeWidget.h -o moc_MainTreeWidget.cpp

moc_LocalHostWidget.cpp: MainTreeWidget.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		LocalHostWidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include LocalHostWidget.h -o moc_LocalHostWidget.cpp

moc_fdefault.cpp: ../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/label.h \
		smouipageheader.h \
		smouitextline.h \
		fdefault.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include fdefault.h -o moc_fdefault.cpp

moc_fdevice.cpp: ../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		fdevice.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include fdevice.h -o moc_fdevice.cpp

moc_fcomport.cpp: ../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/config.h \
		../LIB/fcomport.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../LIB/fcomport.h -o moc_fcomport.cpp

moc_LogTree.cpp: ../LIB/LogTree.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../LIB/LogTree.h -o moc_LogTree.cpp

moc_config.cpp: ../LIB/zvvlib.h \
		../LIB/config.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../LIB/config.h -o moc_config.cpp

moc_SerialPort.cpp: ../LIB/SerialPort.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../LIB/SerialPort.h -o moc_SerialPort.cpp

moc_g8enum.cpp: ../LIB/zvvlib.h \
		../../Data/GlobalStatusErrorCodes.h \
		../LIB/g8enum.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../LIB/g8enum.h -o moc_g8enum.cpp

moc_desettings.cpp: ../LIB/config.h \
		../LIB/zvvlib.h \
		MainWindow.h \
		MainTreeWidget.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/LogTree.h \
		desettings.h \
		desettings.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include desettings.h -o moc_desettings.cpp

moc_label.cpp: ../LIB/label.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../LIB/label.h -o moc_label.cpp

moc_smoui.cpp: smoui.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Examples/QT/DE -I/tmp/Examples/QT/LIB -I/tmp/Examples/Data -I/tmp/Examples/AVR/Macros -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include smoui.h -o moc_smoui.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		MainTreeWidget.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/LogTree.h \
		desettings.h \
		../LIB/config.h \
		MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

toolbar.o: toolbar.cpp app_config.h \
		../LIB/zvvlib.h \
		toolbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolbar.o toolbar.cpp

MainWindow.o: MainWindow.cpp app_config.h \
		../LIB/zvvlib.h \
		MainWindow.h \
		MainTreeWidget.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/LogTree.h \
		desettings.h \
		../LIB/config.h \
		toolbar.h \
		LocalHostWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

MainTreeWidget.o: MainTreeWidget.cpp app_config.h \
		../LIB/zvvlib.h \
		MainTreeWidget.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		LocalHostWidget.h \
		fdefault.h \
		../LIB/label.h \
		smouipageheader.h \
		smouitextline.h \
		fdevice.h \
		../LIB/LogTree.h \
		../LIB/fcomport.h \
		../LIB/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainTreeWidget.o MainTreeWidget.cpp

LocalHostWidget.o: LocalHostWidget.cpp app_config.h \
		../LIB/zvvlib.h \
		LocalHostWidget.h \
		MainTreeWidget.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/delib.h \
		../LIB/Smo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LocalHostWidget.o LocalHostWidget.cpp

fdefault.o: fdefault.cpp app_config.h \
		../LIB/zvvlib.h \
		fdefault.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/label.h \
		smouipageheader.h \
		smouitextline.h \
		../LIB/delib.h \
		../LIB/Smo.h \
		../LIB/LogTree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fdefault.o fdefault.cpp

fdevice.o: fdevice.cpp app_config.h \
		../LIB/zvvlib.h \
		../LIB/delib.h \
		../LIB/Smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/smo.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/SerialPort.h \
		fdevice.h \
		../LIB/LogTree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fdevice.o fdevice.cpp

desettings.o: desettings.cpp desettings.h \
		../LIB/config.h \
		../LIB/zvvlib.h \
		MainWindow.h \
		MainTreeWidget.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/LogTree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o desettings.o desettings.cpp

smo.o: ../LIB/smo.cpp ../LIB/Smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/smo.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/SerialPort.h \
		../LIB/LogTree.h \
		../LIB/realtime32.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smo.o ../LIB/smo.cpp

zvvlib.o: ../LIB/zvvlib.cpp ../LIB/zvvlib.h \
		../LIB/LogTree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zvvlib.o ../LIB/zvvlib.cpp

deviceinfo.o: ../LIB/deviceinfo.cpp ../LIB/deviceinfo.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/SerialPort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o deviceinfo.o ../LIB/deviceinfo.cpp

deplugin.o: ../LIB/deplugin.cpp ../LIB/deplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o deplugin.o ../LIB/deplugin.cpp

fcomport.o: ../LIB/fcomport.cpp ../LIB/fcomport.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/config.h \
		../LIB/smolib.h \
		../LIB/LogTree.h \
		../LIB/delib.h \
		../LIB/Smo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fcomport.o ../LIB/fcomport.cpp

fmessage.o: ../LIB/fmessage.cpp ../LIB/fmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fmessage.o ../LIB/fmessage.cpp

smolib.o: ../LIB/smolib.cpp ../LIB/SerialPort.h \
		../LIB/smolib.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h \
		../LIB/LogTree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smolib.o ../LIB/smolib.cpp

LogTree.o: ../LIB/LogTree.cpp ../LIB/LogTree.h \
		../LIB/treelib.h \
		../LIB/zvvlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LogTree.o ../LIB/LogTree.cpp

treelib.o: ../LIB/treelib.cpp ../LIB/treelib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o treelib.o ../LIB/treelib.cpp

config.o: ../LIB/config.cpp ../LIB/config.h \
		../LIB/zvvlib.h \
		../LIB/LogTree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o ../LIB/config.cpp

SerialPort.o: ../LIB/SerialPort.cpp ../LIB/SerialPort.h \
		../LIB/zvvlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SerialPort.o ../LIB/SerialPort.cpp

CRC.o: ../../AVR/Macros/CRC.c ../../AVR/Macros/CRC.h \
		../LIB/ZvvCompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../LIB/zvvcompiler.h \
		../../AVR/Macros/CRC8_lib.h \
		../../AVR/Macros/CRC8_lib.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o CRC.o ../../AVR/Macros/CRC.c

Offseters.o: ../../AVR/Macros/Offseters.c ../../AVR/Macros/Offseters.h \
		../LIB/ZvvCompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../LIB/zvvcompiler.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Offseters.o ../../AVR/Macros/Offseters.c

g8enum.o: ../LIB/g8enum.cpp ../LIB/g8enum.h \
		../LIB/zvvlib.h \
		../../Data/GlobalStatusErrorCodes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o g8enum.o ../LIB/g8enum.cpp

label.o: ../LIB/label.cpp ../LIB/label.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o label.o ../LIB/label.cpp

smoui.o: smoui.cpp smoui.h \
		smouipageheader.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smouitextline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smoui.o smoui.cpp

smouipageheader.o: smouipageheader.cpp smouipageheader.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smouipageheader.o smouipageheader.cpp

smouitextline.o: smouitextline.cpp smouitextline.h \
		../LIB/smo.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h \
		../../Data/zvvDataTypes.h \
		../../Data/GlobalStatusErrorCodes.h \
		../../Data/SmoRecord.h \
		../LIB/ZvvCompiler.h \
		../../Data/SmoBusData.h \
		app_config.h \
		../LIB/zvvlib.h \
		../../Data/NetFrameTypes.h \
		../LIB/deviceinfo.h \
		../LIB/SerialPort.h \
		../LIB/deplugin.h \
		../../AVR/Macros/CRC.h \
		../../AVR/Macros/Offseters.h \
		../LIB/g8enum.h \
		smoui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smouitextline.o smouitextline.cpp

byte.o: ../LIB/byte.cpp ../LIB/byte.h \
		../../Data/zvvDataTypes.h \
		../LIB/zvvcompiler.h \
		../LIB/compiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o byte.o ../LIB/byte.cpp

realtime32.o: ../LIB/realtime32.cpp ../LIB/realtime32.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o realtime32.o ../LIB/realtime32.cpp

qrc_DE.o: qrc_DE.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_DE.o qrc_DE.cpp

moc_toolbar.o: moc_toolbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolbar.o moc_toolbar.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_MainTreeWidget.o: moc_MainTreeWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainTreeWidget.o moc_MainTreeWidget.cpp

moc_LocalHostWidget.o: moc_LocalHostWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LocalHostWidget.o moc_LocalHostWidget.cpp

moc_fdefault.o: moc_fdefault.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fdefault.o moc_fdefault.cpp

moc_fdevice.o: moc_fdevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fdevice.o moc_fdevice.cpp

moc_fcomport.o: moc_fcomport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fcomport.o moc_fcomport.cpp

moc_LogTree.o: moc_LogTree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LogTree.o moc_LogTree.cpp

moc_config.o: moc_config.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_config.o moc_config.cpp

moc_SerialPort.o: moc_SerialPort.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SerialPort.o moc_SerialPort.cpp

moc_g8enum.o: moc_g8enum.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_g8enum.o moc_g8enum.cpp

moc_desettings.o: moc_desettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_desettings.o moc_desettings.cpp

moc_label.o: moc_label.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_label.o moc_label.cpp

moc_smoui.o: moc_smoui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_smoui.o moc_smoui.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

